CREATE TABLE combinations (
  id INT AUTO_INCREMENT PRIMARY KEY,
  item_id INT NOT NULL,
  combination JSON NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE
);